name: 'Mastodon Backup Action'
description: 'A GitHub Action to backup Mastodon posts'
author: 'Schwitzd'
inputs:
  mastodon_access_token:
    description: 'Mastodon access token'
    required: true
    type: secrets
  mastodon_base_url:
    description: 'Mastodon instance base URL'
    required: true
    type: string