name: Backup Mastodon Posts

on:
  schedule:
    - cron: '0 0 * * 5'  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  backup:
    runs-on: ubuntu-latest
    environment: Mastodon

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Calculate current date and time
      id: current_datetime
      run: |
        echo "YEAR=$(date -u +'%Y')" >> $GITHUB_ENV
        echo "DAY=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "HOUR=$(date -u +'%H:%M')"  >> $GITHUB_ENV

    - name: Backup Mastodon posts
      env:
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        MASTODON_BASE_URL: ${{ vars.MASTODON_BASE_URL }}
      run: python mastodon_backup.py

    - name: Commit and push backup
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add mastodon_posts_${year}.json
        git commit -m "Backup on ${day} ${hour}"
        git push
